spring:
  config:
    activate:
      on-profile: postgresql
  application:
    name: Spring-Test-Bed

  # Primary DataSource (PostgreSQL)
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/high_performance_java_persistence
    username: postgres
    password: admin
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
      ddl-auto: validate
    properties:
      hibernate:
        jdbc:
          batch_size: 20
          order_inserts: true
          order_updates: true
        connection:
          provider_disables_autocommit: true

logging:
  level:
    net.ttddyy.dsproxy.listener: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    com.side: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

##

---

spring:
  config:
    activate:
      on-profile: h2
  application:
    name: Spring-Test-Bed

  # H2 DataSource for Test Environment
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2: # H2 ?? ??? spring.h2 ??? ???
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true # ?? PC?? H2 ?? ?? ?? (??? ??)

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: create-drop # H2? ?? ????? create-drop

logging:
  level:
    net.ttddyy.dsproxy.listener: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.transaction: DEBUG
    com.side: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"